//==================================================
// This file contains the Excluded objects
// Generated By User: sontd
// Format Version: 2
// Date: Wed Mar 17 17:52:40 2021
// ExclMode: default
//==================================================
CHECKSUM: "327549882 3690810522"
INSTANCE: spi_slv_top._spi_slv.spictrl
Toggle 1to0 RX_BUSY "logic RX_BUSY"
Toggle 0to1 RX_BUSY "logic RX_BUSY"
CHECKSUM: "3349735992 2590840078"
INSTANCE: spi_slv_top._spi_slv
Toggle 1to0 RX_BUSY "net RX_BUSY"
Toggle 0to1 RX_BUSY "net RX_BUSY"
CHECKSUM: "3613031468 364067248"
INSTANCE: spi_slv_top._rtl_apb_intf
Toggle 1to0 PSLVERR "logic PSLVERR"
Toggle 0to1 PSLVERR "logic PSLVERR"
CHECKSUM: "4288311846 4266683935"
INSTANCE: spi_slv_top._spi_slv.apbctrl
ANNOTATION: " cannot happen this case "
Condition 15 "2740895290" "(r_psel[0] && ((!r_psel[1])) && (r_paddr == 3'h6) && r_pwrite) 1 -1"
ANNOTATION: " cannot happen this case "
Condition 8 "1538409700" "(r_psel[0] && ((!r_psel[1])) && (r_paddr == 3'h6) && r_pwrite) 1 -1"
CHECKSUM: "327549882 3555902163"
INSTANCE: spi_slv_top._spi_slv.spictrl
ANNOTATION: " srstn and r_rst_sync are depend reset, cannot happen this case "
Condition 2 "3605306978" "(((!r_rst_sync[0])) || ((!_intf_clkrst.srstn))) 1 -1"
ANNOTATION: " srstn and r_rst_sync are depend reset, cannot happen this case "
Condition 5 "3605306978" "(((!r_rst_sync[0])) || ((!_intf_clkrst.srstn))) 1 -1"
ANNOTATION: " srstn and r_rst_sync are depend reset, cannot happen this case "
Condition 1 "3252218618" "(((!r_rst_sync[0])) || ((!_intf_clkrst.srstn)) || w_scsn_rise) 1 -1"
CHECKSUM: "327549882 3295593422"
INSTANCE: spi_slv_top._spi_slv.spictrl
ANNOTATION: " RTL description is missing "
Branch 7 "4081298856" "w_scsn_fall" (5) "w_scsn_fall 0,1,0,0,0,0"
